apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: staging

namespace: streamlit-staging

#Container image, uses image name to match the image in the base
images:
- name: public.ecr.aws/z1l0c6l7/simpleapp
  newTag: 1438219ba73c049c7e9b5578bf8d41f4b3d208be
  #newName: my-registry/my-postgres

resources:
- namespace.yaml
- ../../base
patches:
- patch: "- op: replace\n  path: /spec/routes/0/match\n  value: Host(`streamlit-staging.githubcode.space`)
    \  "
  target:
    labelSelector: app.kubernetes.io/type=traefik
