apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: head

namespace: streamlit-head

#Container image, uses image name to match the image in the base
images:
- name: public.ecr.aws/z1l0c6l7/simpleapp
  newTag: fca5cf4d2c175cc7f5d56269276594dc8aab5399
  #newName: my-registry/my-postgres

resources:
- namespace.yaml
- ../../base
patches:
- patch: "- op: replace\n  path: /spec/routes/0/match\n  value: Host(`streamlit-head.githubcode.space`)
    \  "
  target:
    labelSelector: app.kubernetes.io/type=traefik
