apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prod

namespace: streamlit-prod

resources:
  - namespace.yaml
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`streamlit-prod.githubcode.space`)   
    target:
      labelSelector: "app.kubernetes.io/type=traefik"
# components:
#   - ../../components/external_db
#   - ../../components/ldap
