apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prod

namespace: streamlit-prod

#Container image, uses image name to match the image in the base
images:
- name: public.ecr.aws/z1l0c6l7/simpleapp
  newTag: "16"
  #newName: my-registry/my-postgres

resources:
  - namespace.yaml
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`streamlit-prod.githubcode.space`)   
    target:
      labelSelector: "app.kubernetes.io/type=traefik"
# components:
#   - ../../components/external_db
#   - ../../components/ldap
