apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prod

namespace: streamlit-prod

#Container image, uses image name to match the image in the base
images:
- name: public.ecr.aws/z1l0c6l7/simpleapp
  newTag: 7ec9cf6a6546375844d6ea80a3148bae063132c9
  #newName: my-registry/my-postgres

resources:
- namespace.yaml
- ../../base
patches:
- patch: "- op: replace\n  path: /spec/routes/0/match\n  value: Host(`streamlit-prod.githubcode.space`)
    \  "
  target:
    labelSelector: app.kubernetes.io/type=traefik
