apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: streamlit-staging
  name: streamlit-ingressroute
  labels:
    app.kubernetes.io/type: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`streamlit-staging.githubcode.space`)
      kind: Rule
      services:
        - name: streamlit-service
          port: 80
  tls:
    secretName: letsencrypt-production-tls