# $BASE/kustomization.yaml
commonLabels:
  app: streamlit

#Container image, uses image name to match the image in the base
images:
- name: public.ecr.aws/z1l0c6l7/simpleapp
  newTag: b007df8000c0779c44fe739436fc570944d86549
  #newName: my-registry/my-postgres

resources:
- limit.yaml
- deployment.yaml
- service.yaml
- ingress-route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
