# $BASE/kustomization.yaml
commonLabels:
  app: streamlit

#Container image, uses image name to match the image in the base
images:
- name: public.ecr.aws/z1l0c6l7/simpleapp
  newTag: "18"
  #newName: my-registry/my-postgres

resources:
- limit.yaml
- deployment.yaml
- service.yaml
- ingress-route.yaml