apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 256Mi
      cpu: "0.3"
    defaultRequest:
      memory: 100Mi
      cpu: "0.1"
    type: Container